---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-flooding-kr-tls
  namespace: traefik
spec:
  secretName: api-flooding-kr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.flooding.kr
