apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "flooding-server.fullname" . }}
  labels:
    {{- include "flooding-server.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "flooding-server.fullname" . }}
          port: {{ .Values.service.port }}
