apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "flooding-server.fullname" . }}
  labels:
    {{- include "flooding-server.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: {{ if .Values.ingress.extraHosts -}}
        Host(`{{ .Values.ingress.host }}`){{ range .Values.ingress.extraHosts }} || Host(`{{ . }}`){{ end }}
      {{- else -}}
        Host(`{{ .Values.ingress.host }}`)
      {{- end }}
      kind: Rule
      services:
        - name: {{ include "flooding-server.fullname" . }}
          port: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
